version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    ports:
      - '5433:5432'  # <--- แก้ตัวหน้าเป็น 5433
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: elderly_db